version: 2.0.{build}
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: CommonAssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- cmd: >-
    dotnet restore

    dotnet pack /p:PackageVersion=%APPVEYOR_BUILD_VERSION%"
test:
  assemblies:
    only:
    - tests\v4.6\bin\Release\Redlock.CSharp.Tests.dll
artifacts:
- path: redlock-cs-async.*.nupkg
