version: 2.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: CommonAssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  project: redlock-cs.sln
  verbosity: minimal
after_build:
- cmd: nuget pack redlock-cs.nuspec -Properties "version=%APPVEYOR_BUILD_VERSION%"
test:
  assemblies: tests\v4.5\bin\Release\Redlock.CSharp.Tests.dll
  assemblies: tests\v4.6\bin\Release\Redlock.CSharp.Tests.dll
artifacts:
- path: redlock-cs-async.*.nupkg